name: sample-workflow

on:
  push:

jobs:
  script-job:
    runs-on: ubuntu-24.04-arm
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Run a one-line script
        uses: actions/script@v7
        with:
          result-encoding: string
          retries: 3
          script: consloe.log(context)
          