name: sample-workflow

on:
  push:

jobs:
  script-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Run a one-line script
        uses: actions/script@v7
        with:
          script: return "Hello!"